spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market_v0?serverTimezone=UTC&characterEncoding=UTF-8
    # market_v0: 스키마 이름
    username: root
    password: capstone

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # 얘도 sql 문을 보여주지만 sout 으로 하기 때문에 않좋다.
        # show_sql: true
        format_sql: true

logging:
  level:
    # hibernate 가 생성하는 sql 문을 모두 보여준다.
    org.hibernate.SQL: debug
    org.hibernate.type: trace